# Generated by Django 4.0.4 on 2022-05-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
